# Site settings
title: Duck Group
email: 
description: > # this means to ignore newlines until "baseurl:"
  A Group For Ducks
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://duckgroup.xyz" # the base hostname & protocol for your site
twitter_username: decoratedbug
github_username:  decoratedbug

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Flappy Duck
    link: flappyduck
  option2:
    name: Games
    link: games.htm

disqus: false
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
